name: CD for main push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying to production"
          echo "Deployed to production"
