name: CD for main push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm i
      - name: Lint
        run: pnpm lint
  build:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm i
      - name: Lint
        run: pnpm build
  deploy:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying to production"
          echo "Deployed to production"
