name: Lint
on:
  workflow_call:

jobs:
  lint:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm i
      - name: Lint
        run: pnpm lint
